name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps (CI minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
          # if you don't have requirements-ci.txt, you can use requirements.txt instead
      - name: Lint
        run: |
          pip install ruff
          ruff check .
      - name: Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest -q
